---@module 'luassert'

_TEST = true
local platform = require("unrealium.core.platform")
local tUtil = require("tests.test_util")

describe("modules.generate", function()
	describe("gen_project_files_cmd", function()
		it("returns cmd array with correct args", function()
			local cfg = tUtil.mock_config()
			local result = platform.gen_project_files_cmd(cfg)
			assert.truthy(result)
			assert.truthy(result.cmd)
			assert.truthy(result.cwd)
			local cmd_str = table.concat(result.cmd, " ")
			assert.matches("GenerateProjectFiles", cmd_str)
			assert.matches("-projectfiles", cmd_str)
			assert.matches("-Makefile", cmd_str)
			assert.matches("-game", cmd_str)
			assert.matches("-engine", cmd_str)
		end)
	end)

	describe("gen_clang_database_cmd", function()
		it("returns correct Project mode command", function()
			local cfg = tUtil.mock_config()
			local result = platform.gen_clang_database_cmd(cfg, "Project")
			assert.truthy(result)
			assert.truthy(result.cmd)
			assert.truthy(result.cwd)
			local cmd_str = table.concat(result.cmd, " ")
			assert.matches("RunUBT", cmd_str)
			assert.matches("GenerateClangDatabase", cmd_str)
		end)

		it("returns correct Engine mode command", function()
			local cfg = tUtil.mock_config()
			local result = platform.gen_clang_database_cmd(cfg, "Engine")
			assert.truthy(result)
			local cmd_str = table.concat(result.cmd, " ")
			assert.matches("MyProject", cmd_str)
		end)
	end)
end)
