---@module 'luassert'

_TEST = true
local platform = require("unrealium.core.platform")
local tUtil = require("tests.test_util")

describe("modules.generate", function()
	describe("gen_project_files_command", function()
		it("returns Dispatch command with correct args", function()
			local cfg = tUtil.mock_config()
			local result = platform.gen_project_files_command(cfg)
			assert.truthy(result)
			assert.matches("Dispatch", result.command)
			assert.matches("GenerateProjectFiles", result.command)
			assert.matches("-projectfiles", result.command)
			assert.matches("-Makefile", result.command)
			assert.matches("-game", result.command)
			assert.matches("-engine", result.command)
		end)
	end)

	describe("gen_clang_database_command", function()
		it("returns correct Project mode command", function()
			local cfg = tUtil.mock_config()
			local result = platform.gen_clang_database_command(cfg, "Project")
			assert.truthy(result)
			assert.matches("Dispatch", result.command)
			assert.matches("RunUBT", result.command)
			assert.matches("GenerateClangDatabase", result.command)
			assert.truthy(result.makeprg)
		end)

		it("returns correct Engine mode command", function()
			local cfg = tUtil.mock_config()
			local result = platform.gen_clang_database_command(cfg, "Engine")
			assert.truthy(result)
			assert.matches("MyProject", result.command)
		end)
	end)
end)
