---@module 'luassert'

_TEST = true
local job = require("unrealium.core.job")

describe("core.job", function()
	before_each(function()
		job._reset()
	end)

	describe("parse_progress", function()
		it("parses @progress pattern", function()
			local result = job._parse_progress("@progress 'Compiling' 45%")
			assert.truthy(result)
			assert.equals(45, result.percentage)
			assert.equals("Compiling", result.label)
		end)

		it("parses [N/M] pattern", function()
			local result = job._parse_progress("[3/10] Building something")
			assert.truthy(result)
			assert.equals(30, result.percentage)
			assert.equals("[3/10]", result.label)
		end)

		it("returns nil for non-progress lines", function()
			assert.is_nil(job._parse_progress("just a regular line"))
		end)

		it("handles [0/N] as 0%", function()
			local result = job._parse_progress("[0/5] Starting")
			assert.truthy(result)
			assert.equals(0, result.percentage)
		end)
	end)

	describe("parse_diagnostic", function()
		it("parses GCC/Clang format with column", function()
			local result = job._parse_diagnostic("/path/file.cpp:42:10: error: undeclared identifier")
			assert.truthy(result)
			assert.equals("/path/file.cpp", result.file)
			assert.equals(42, result.lnum)
			assert.equals(10, result.col)
			assert.equals("error", result.type)
			assert.equals("undeclared identifier", result.text)
		end)

		it("parses GCC/Clang format without column", function()
			local result = job._parse_diagnostic("/path/file.cpp:42: warning: unused variable")
			assert.truthy(result)
			assert.equals("/path/file.cpp", result.file)
			assert.equals(42, result.lnum)
			assert.is_nil(result.col)
			assert.equals("warning", result.type)
		end)

		it("parses MSVC format", function()
			local result = job._parse_diagnostic("C:\\src\\file.cpp(42): error C2065: undeclared")
			assert.truthy(result)
			assert.equals("C:\\src\\file.cpp", result.file)
			assert.equals(42, result.lnum)
			assert.equals("error", result.type)
		end)

		it("returns nil for non-diagnostic lines", function()
			assert.is_nil(job._parse_diagnostic("Building target MyProject..."))
		end)
	end)

	describe("buffer_lines", function()
		it("handles complete lines", function()
			local lines, remainder = job._buffer_lines("", { "line1", "line2", "" })
			assert.same({ "line1", "line2" }, lines)
			assert.equals("", remainder)
		end)

		it("handles partial last line", function()
			local lines, remainder = job._buffer_lines("", { "line1", "partial" })
			assert.same({ "line1" }, lines)
			assert.equals("partial", remainder)
		end)

		it("prepends remainder to first chunk", function()
			local lines, remainder = job._buffer_lines("start_", { "end_line1", "line2", "" })
			assert.same({ "start_end_line1", "line2" }, lines)
			assert.equals("", remainder)
		end)

		it("handles single partial element", function()
			local lines, remainder = job._buffer_lines("prev", { "more" })
			assert.same({}, lines)
			assert.equals("prevmore", remainder)
		end)
	end)
end)
