name: Release

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    uses: folke/github/.github/workflows/ci.yml@main
    secrets: inherit
    with:
      plugin: unrealium.nvim
      repo: jacksonhvisuals/unrealium.nvim
      docs: false
